version: "3.7"

services:
  shell: 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user_name: ${USER}
    hostname: ${HOSTNAME}
    env_file: .env
    ports: 
      - 8080:80
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 100M
