version: "3"

services:
  shell: 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user_name: ${USER}
    hostname: ${HOSTNAME}
    env_file: .env
    ports: 
      - 8080:80